spring:
  config:
    activate:
      on-profile: ssl
  kafka:
    topic:  library-events
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/Users/dilipbandlasundarraj/Dilip/code-with-dilip/kafka-cluster-ssl/secrets/kafka.producer.truststore.jks
        trust-store-password: confluent
        key-store-location: file:/Users/dilipbandlasundarraj/Dilip/code-with-dilip/kafka-cluster-ss/secrets/kafka.producer.keystore.jks
        key-store-password: confluent
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      auto-offset-reset: latest
      ssl:
        trust-store-location: file:/Users/dilipbandlasundarraj/Dilip/code-with-dilip/kafka-cluster-ssl/secrets/kafka.consumer.truststore.jks
        trust-store-password: confluent
#        key-store-location: file:/Users/dilipbandlasundarraj/Dilip/code-with-dilip/kafka-cluster-ssl/secrets/kafka.consumer.keystore.jks
#        key-store-password: confluent
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:

    admin:
      properties:
        bootstrap.servers: localhost:9092